from pydantic import BaseModel, Field
from typing import List


class ExecutionLogEntry(BaseModel):
    step: str = Field(description="Name of the step")
    status: str = Field(description="success, failed, or skipped")
    details: str = Field(default="", description="Additional information")


class AgentResponse(BaseModel):
    tasks: List[dict] = Field(description="Task list generated by the planner")
    assumptions: List[str] = Field(description="Assumptions made by the agent")
    summary: str = Field(description="Summary of what was done")
    document_path: str = Field(description="Path to the generated .docx file")
    execution_log: List[ExecutionLogEntry] = Field(description="Execution trace")
